-- Update recipes with image URLs
-- Run in Supabase SQL Editor after the seed data

UPDATE recipes SET image_url = '/recipes/spanish-zucchini-tortilla.jpeg' WHERE name = 'Spanish Zucchini Tortilla';
UPDATE recipes SET image_url = '/recipes/omelet-wraps.jpeg' WHERE name = 'Omelet Wraps';
UPDATE recipes SET image_url = '/recipes/egg-turkey-stuffed-peppers.jpeg' WHERE name = 'Egg & Turkey Stuffed Peppers';
UPDATE recipes SET image_url = '/recipes/smoked-salmon-feta-asparagus-omelet.jpeg' WHERE name = 'Smoked Salmon, Feta & Asparagus Omelet';
UPDATE recipes SET image_url = '/recipes/high-protein-blueberry-pancakes.jpeg' WHERE name = 'High Protein Blueberry Pancakes';
UPDATE recipes SET image_url = '/recipes/eggs-fried-on-tomatoes-with-tuna.jpeg' WHERE name = 'Eggs Fried On Tomatoes With Tuna';
UPDATE recipes SET image_url = '/recipes/summer-smoothie-protein-bowl.jpeg' WHERE name = 'Summer Smoothie Protein Bowl';
UPDATE recipes SET image_url = '/recipes/spinach-shakshuka.jpeg' WHERE name = 'Spinach Shakshuka';
UPDATE recipes SET image_url = '/recipes/salmon-tartar-with-avocado-mango.jpeg' WHERE name = 'Salmon Tartar With Avocado & Mango';
UPDATE recipes SET image_url = '/recipes/tuna-salad-lettuce-wraps.jpeg' WHERE name = 'Tuna Salad Lettuce Wraps';
UPDATE recipes SET image_url = '/recipes/chicken-orange-walnut-salad.jpeg' WHERE name = 'Chicken, Orange & Walnut Salad';
UPDATE recipes SET image_url = '/recipes/salmon-peach-salad.jpeg' WHERE name = 'Salmon & Peach Salad';
UPDATE recipes SET image_url = '/recipes/tuna-broccoli-salad-with-honey-vinaigrette.jpeg' WHERE name = 'Tuna & Broccoli Salad With Honey Vinaigrette';
UPDATE recipes SET image_url = '/recipes/grilled-chicken-pineapple-salad.jpeg' WHERE name = 'Grilled Chicken & Pineapple Salad';
UPDATE recipes SET image_url = '/recipes/waldorf-chicken-salad.jpeg' WHERE name = 'Waldorf Chicken Salad';
UPDATE recipes SET image_url = '/recipes/tuna-quinoa-toss-salad.jpeg' WHERE name = 'Tuna & Quinoa Toss Salad';
UPDATE recipes SET image_url = '/recipes/salmon-couscous-salad.jpeg' WHERE name = 'Salmon & Couscous Salad';
UPDATE recipes SET image_url = '/recipes/post-workout-potato-pancakes-with-cottage-cheese.jpeg' WHERE name = 'Post-Workout Potato Pancakes With Cottage Cheese';
UPDATE recipes SET image_url = '/recipes/miso-salmon-with-zucchini-noodles.jpeg' WHERE name = 'Miso Salmon With Zucchini Noodles';
UPDATE recipes SET image_url = '/recipes/moroccan-cod-bulgur-salad.jpeg' WHERE name = 'Moroccan Cod & Bulgur Salad';
UPDATE recipes SET image_url = '/recipes/turkey-broccoli-stir-fry.jpeg' WHERE name = 'Turkey & Broccoli Stir Fry';
UPDATE recipes SET image_url = '/recipes/baked-salmon-with-zoodles-quinoa.jpeg' WHERE name = 'Baked Salmon With Zoodles & Quinoa';
UPDATE recipes SET image_url = '/recipes/chicken-thighs-with-hoisin-rice.jpeg' WHERE name = 'Chicken Thighs With Hoisin Rice';
UPDATE recipes SET image_url = '/recipes/chinese-pork-stir-fry-with-pineapple.jpeg' WHERE name = 'Chinese Pork Stir-Fry With Pineapple';
UPDATE recipes SET image_url = '/recipes/slow-cooker-chicken-fajitas.jpeg' WHERE name = 'Slow Cooker Chicken Fajitas';
UPDATE recipes SET image_url = '/recipes/creamy-chicken-mushroom-tomato-pasta.jpeg' WHERE name = 'Creamy Chicken, Mushroom & Tomato Pasta';
UPDATE recipes SET image_url = '/recipes/cajun-beef-veg-rice.jpeg' WHERE name = 'Cajun Beef & Veg Rice';
UPDATE recipes SET image_url = '/recipes/chinese-style-shrimps-veg.jpeg' WHERE name = 'Chinese Style Shrimps & Veg';
UPDATE recipes SET image_url = '/recipes/zesty-turkey-meatballs-with-couscous-salad.jpeg' WHERE name = 'Zesty Turkey Meatballs With Couscous Salad';
UPDATE recipes SET image_url = '/recipes/honey-lime-glazed-salmon-with-pineapple-rice.jpeg' WHERE name = 'Honey & Lime Glazed Salmon With Pineapple Rice';
UPDATE recipes SET image_url = '/recipes/simple-chicken-curry-with-saffron-rice.jpeg' WHERE name = 'Simple Chicken Curry With Saffron Rice';
UPDATE recipes SET image_url = '/recipes/baked-salmon-tray-with-rice-tomatoes.jpeg' WHERE name = 'Baked Salmon Tray With Rice & Tomatoes';
UPDATE recipes SET image_url = '/recipes/one-pot-turkey-chili-with-rice.jpeg' WHERE name = 'One Pot Turkey Chili With Rice';
UPDATE recipes SET image_url = '/recipes/mexican-fried-rice.jpeg' WHERE name = 'Mexican Fried Rice';
UPDATE recipes SET image_url = '/recipes/beef-green-beans-pasta-in-soy-sauce.jpeg' WHERE name = 'Beef & Green Beans Pasta In Soy Sauce';
UPDATE recipes SET image_url = '/recipes/chicken-mango-stir-fry.jpeg' WHERE name = 'Chicken & Mango Stir Fry';
UPDATE recipes SET image_url = '/recipes/salmon-teriyaki-with-green-beans-sweetcorn-rice.jpeg' WHERE name = 'Salmon Teriyaki With Green Beans & Sweetcorn Rice';
UPDATE recipes SET image_url = '/recipes/chicken-orange-stir-fry.jpeg' WHERE name = 'Chicken Orange Stir Fry';
UPDATE recipes SET image_url = '/recipes/pesto-pasta-with-tuna-almonds.jpeg' WHERE name = 'Pesto Pasta With Tuna & Almonds';
UPDATE recipes SET image_url = '/recipes/sweet-and-sour-pork-stir-fry.jpeg' WHERE name = 'Sweet And Sour Pork Stir-Fry';
UPDATE recipes SET image_url = '/recipes/pepper-steak.jpeg' WHERE name = 'Pepper Steak';
UPDATE recipes SET image_url = '/recipes/quick-easy-meatballs.jpeg' WHERE name = 'Quick & Easy Meatballs';
UPDATE recipes SET image_url = '/recipes/quick-beef-chow-mein.jpeg' WHERE name = 'Quick Beef Chow Mein';
UPDATE recipes SET image_url = '/recipes/simple-chili-sweet-potato-chips.jpeg' WHERE name = 'Simple Chili & Sweet Potato Chips';
UPDATE recipes SET image_url = '/recipes/cherry-sorbet.jpeg' WHERE name = 'Cherry Sorbet';
UPDATE recipes SET image_url = '/recipes/protein-fruit-bowls.jpeg' WHERE name = 'Protein Fruit Bowls';
UPDATE recipes SET image_url = '/recipes/matcha-chia-pudding.jpeg' WHERE name = 'Matcha Chia Pudding';
UPDATE recipes SET image_url = '/recipes/raspberry-protein-smoothie.jpeg' WHERE name = 'Raspberry Protein Smoothie';
UPDATE recipes SET image_url = '/recipes/green-glow-protein-smoothie.jpeg' WHERE name = 'Green Glow Protein Smoothie';
UPDATE recipes SET image_url = '/recipes/vanilla-coffee-protein-smoothie.jpeg' WHERE name = 'Vanilla & Coffee Protein Smoothie';
UPDATE recipes SET image_url = '/recipes/antioxidant-blueberry-protein-smoothie.jpeg' WHERE name = 'Antioxidant Blueberry Protein Smoothie';
UPDATE recipes SET image_url = '/recipes/cinnamon-roll-protein-smoothie.jpeg' WHERE name = 'Cinnamon Roll Protein Smoothie';
UPDATE recipes SET image_url = '/recipes/turmeric-poached-egg.jpeg' WHERE name = 'Turmeric Poached Egg';
UPDATE recipes SET image_url = '/recipes/omelet-with-cottage-cheese-basil.jpeg' WHERE name = 'Omelet With Cottage Cheese & Basil';
UPDATE recipes SET image_url = '/recipes/herby-breakfast-sausages.jpeg' WHERE name = 'Herby Breakfast Sausages';
UPDATE recipes SET image_url = '/recipes/avocado-egg-paste.jpeg' WHERE name = 'Avocado & Egg Paste';
UPDATE recipes SET image_url = '/recipes/cottage-cheese-protein-pancakes.jpeg' WHERE name = 'Cottage Cheese Protein Pancakes';
UPDATE recipes SET image_url = '/recipes/tropical-gluten-free-granola.jpeg' WHERE name = 'Tropical Gluten Free Granola';
UPDATE recipes SET image_url = '/recipes/smoked-mackerel-egg-paste.jpeg' WHERE name = 'Smoked Mackerel & Egg Paste';
UPDATE recipes SET image_url = '/recipes/egg-broccoli-ham-muffins.jpeg' WHERE name = 'Egg Broccoli & Ham Muffins';
UPDATE recipes SET image_url = '/recipes/egg-bacon-avocado-bowl.jpeg' WHERE name = 'Egg, Bacon & Avocado Bowl';
UPDATE recipes SET image_url = '/recipes/asian-scrambled-eggs.jpeg' WHERE name = 'Asian Scrambled Eggs';
UPDATE recipes SET image_url = '/recipes/zucchini-fries.jpeg' WHERE name = 'Zucchini Fries';
UPDATE recipes SET image_url = '/recipes/tofu-caesar-summer-rolls.jpeg' WHERE name = 'Tofu Caesar Summer Rolls';
UPDATE recipes SET image_url = '/recipes/sweetcorn-fritters.jpeg' WHERE name = 'Sweetcorn Fritters';
UPDATE recipes SET image_url = '/recipes/tofu-green-peas-paste.jpeg' WHERE name = 'Tofu & Green Peas Paste';
UPDATE recipes SET image_url = '/recipes/black-bean-hummus.jpeg' WHERE name = 'Black Bean Hummus';
UPDATE recipes SET image_url = '/recipes/kale-tofu-salad-with-peanut-butter-dressing.jpeg' WHERE name = 'Kale & Tofu Salad With Peanut Butter Dressing';
UPDATE recipes SET image_url = '/recipes/smoked-salmon-strawberry-salad.jpeg' WHERE name = 'Smoked Salmon & Strawberry Salad';
UPDATE recipes SET image_url = '/recipes/cucumber-avocado-chicken-salad.jpeg' WHERE name = 'Cucumber, Avocado & Chicken Salad';
UPDATE recipes SET image_url = '/recipes/pear-cured-ham-walnut-salad.jpeg' WHERE name = 'Pear, Cured Ham & Walnut Salad';
UPDATE recipes SET image_url = '/recipes/easy-greek-zoodle-salad.jpeg' WHERE name = 'Easy Greek Zoodle Salad';
UPDATE recipes SET image_url = '/recipes/crushed-cucumber-salad-with-salmon.jpeg' WHERE name = 'Crushed Cucumber Salad With Salmon';
UPDATE recipes SET image_url = '/recipes/healthy-coronation-chicken-salad.jpeg' WHERE name = 'Healthy Coronation Chicken Salad';
UPDATE recipes SET image_url = '/recipes/grilled-vegetable-salad-with-tuna.jpeg' WHERE name = 'Grilled Vegetable Salad With Tuna';
UPDATE recipes SET image_url = '/recipes/low-carb-turkey-salad.jpeg' WHERE name = 'Low Carb Turkey Salad';
UPDATE recipes SET image_url = '/recipes/salmon-spring-rolls.jpeg' WHERE name = 'Salmon Spring Rolls';
UPDATE recipes SET image_url = '/recipes/cod-with-creamy-zoodles.jpeg' WHERE name = 'Cod With Creamy Zoodles';
UPDATE recipes SET image_url = '/recipes/jerk-chicken-with-cauliflower-rice.jpeg' WHERE name = 'Jerk Chicken With Cauliflower Rice';
UPDATE recipes SET image_url = '/recipes/grilled-lemon-chicken-salad.jpeg' WHERE name = 'Grilled Lemon Chicken Salad';
UPDATE recipes SET image_url = '/recipes/homemade-quinoa-chicken-nuggets.jpeg' WHERE name = 'Homemade Quinoa Chicken Nuggets';
UPDATE recipes SET image_url = '/recipes/sesame-ginger-beef-with-zucchini-noodles.jpeg' WHERE name = 'Sesame & Ginger Beef With Zucchini Noodles';
UPDATE recipes SET image_url = '/recipes/tom-yum-soup-with-shrimps.jpeg' WHERE name = 'Tom Yum Soup With Shrimps';
UPDATE recipes SET image_url = '/recipes/warm-salmon-quinoa-salad.jpeg' WHERE name = 'Warm Salmon & Quinoa Salad';
UPDATE recipes SET image_url = '/recipes/strawberry-protein-muffins.jpeg' WHERE name = 'Strawberry Protein Muffins';
UPDATE recipes SET image_url = '/recipes/peanut-butter-protein-fluff.jpeg' WHERE name = 'Peanut Butter Protein Fluff';
UPDATE recipes SET image_url = '/recipes/low-carb-banana-strawberry-cake.jpeg' WHERE name = 'Low Carb Banana & Strawberry Cake';
UPDATE recipes SET image_url = '/recipes/healthy-ferrero-rocher.jpeg' WHERE name = 'Healthy Ferrero Rocher';
UPDATE recipes SET image_url = '/recipes/fit-almond-energy-balls.jpeg' WHERE name = 'Fit Almond Energy Balls';
UPDATE recipes SET image_url = '/recipes/mocha-truffles.jpeg' WHERE name = 'Mocha Truffles';
UPDATE recipes SET image_url = '/recipes/vegan-creme-brulee.jpeg' WHERE name = 'Vegan Crème Brulee';
UPDATE recipes SET image_url = '/recipes/banana-chocolate-bites.jpeg' WHERE name = 'Banana Chocolate Bites';